### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by enzohnnn** [AlexRussell4/cse15l-lab-reports#2]
**Bug/Input 1**
- [X] Commit screenshot for bug/input 1
- [X] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [X] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [X] Commit screenshot for bug/input 2
- [X] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [X] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [X] Commit screenshot for bug/input 3
- [X] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
- [X] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
Your lab is well written and easy to read. However, for the tasks that I didn't give you credit for, while you did show your output I also want to see you input the command into your terminal and see it spit out that output. Otherwise well done!

Feel free to comment below if you have any questions about the rubric/feedback.

**Comment by AlexRussell4** [comment]
These issues should now be addressed; I replaced the output text with images of the relevant input/output.

**Comment by enzohnnn** [comment]
Good fix!
